package com.practice.todolist.service.mapper;

import com.practice.todolist.controller.dto.StateDTO;
import com.practice.todolist.model.State;

import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:26
*/
@Mapper(componentModel = "spring")
public interface StateMapper {

    State toEntity(StateDTO dto);

    StateDTO toDto(State entity);

}