package com.practice.todolist.service.mapper;

import com.practice.todolist.controller.dto.StateDTO;
import com.practice.todolist.model.State;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:26
*/
@Mapper(componentModel = "spring")
public interface StateMapper {

    @Mapping(source = "name",target = "name")
    State toEntity(StateDTO dto);

    @Mapping(source = "name",target = "name")
    StateDTO toDto(State entity);

}