package com.practice.todolist.service.mapper;

import com.practice.todolist.model.Task;
import com.practice.todolist.controller.dto.TaskDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:26
*/
@Mapper(componentModel = "spring")
public interface TaskMapper {

    Task toEntity(TaskDTO dto);

    TaskDTO toDto(Task entity);

}