package com.practice.todolist.service.mapper;

import com.practice.todolist.model.Todolist;
import com.practice.todolist.controller.dto.TodolistDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:26
*/
@Mapper(componentModel = "spring")
public interface TodolistMapper {

    Todolist toEntity(TodolistDTO dto);

    TodolistDTO toDto(Todolist entity);

}