package com.practice.todolist.controller;

import com.practice.todolist.model.Listed;
import com.practice.todolist.controller.dto.ListedDTO;
import com.practice.todolist.service.ListedService;
import com.practice.todolist.service.mapper.ListedMapper;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:26
*/
@RestController
@RequestMapping("/list-dto/")
public class ListedControllerDTO implements CrudController<ListedDTO,Integer>{

    @Autowired
    private ListedService service;

    private ListedMapper mapper;

    @Override
    public ResponseEntity<ListedDTO> create(@RequestBody ListedDTO dto) {
       Listed entity = mapper.toEntity(dto);
       entity = service.create(entity);
       return ResponseEntity.ok(mapper.toDto(entity));
    }

    @Override
    public ResponseEntity<ListedDTO> update(@RequestBody ListedDTO dto) {
      Listed entity = mapper.toEntity(dto);
       entity = service.update(entity);
       return ResponseEntity.ok(mapper.toDto(entity));
    }

    @Override
    public ResponseEntity<Page<ListedDTO>> read(
            @RequestBody ListedDTO dto,
            @RequestParam("page") Integer page,
            @RequestParam("size") Integer size) {
        Pageable pageable = PageRequest.of(page,size);
        Listed entity = mapper.toEntity(dto);
        Page<ListedDTO> pages = service.read(entity, pageable).map(mapper::toDto);
        return ResponseEntity.ok(pages);
    }

    @Override
    public ResponseEntity<ListedDTO> readOne(@PathVariable("id") Integer primaryKey) {
         Listed entity = service.readOne(primaryKey);
         return ResponseEntity.ok(mapper.toDto(entity));
    }

    @Override
    public void delete(Integer primaryKey) {
        service.delete(primaryKey);
    }
}