package com.practice.todolist.controller;

import com.practice.todolist.model.Listed;
import com.practice.todolist.service.ListedService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:26
*/
@RestController
@RequestMapping("/list/")
public class ListedController implements CrudController<Listed,Integer>{

    @Autowired
    private ListedService service;

    @Override
    public ResponseEntity<Listed> create(@RequestBody Listed entity) {
        return ResponseEntity.ok(service.create(entity));
    }

    @Override
    public ResponseEntity<Listed> update(@RequestBody Listed entity) {
        return ResponseEntity.ok(service.update(entity));
    }

    @Override
    public ResponseEntity<Page<Listed>> read(
            @RequestBody Listed entity,
            @RequestParam("page") Integer page,
            @RequestParam("size") Integer size) {
        Pageable pageable = PageRequest.of(page,size);
        return ResponseEntity.ok(service.read(entity,pageable));
    }

    @Override
    public ResponseEntity<Listed> readOne(@PathVariable("id") Integer primaryKey) {
        return ResponseEntity.ok(service.readOne(primaryKey));
    }

    @Override
    public void delete(Integer primaryKey) {
        service.delete(primaryKey);
    }
}