package com.practice.todolist.controller;

import com.practice.todolist.model.State;
import com.practice.todolist.controller.dto.StateDTO;
import com.practice.todolist.service.StateService;
import com.practice.todolist.service.mapper.StateMapper;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:26
*/
@RestController
@RequestMapping("/state-dto/")
public class StateControllerDTO implements CrudController<StateDTO,Integer>{

    @Autowired
    private StateService service;

    
    private StateMapper mapper;

    @Override
    public ResponseEntity<StateDTO> create(@RequestBody StateDTO dto) {
       State entity = mapper.toEntity(dto);
       entity = service.create(entity);
       return ResponseEntity.ok(mapper.toDto(entity));
    }

    @Override
    public ResponseEntity<StateDTO> update(@RequestBody StateDTO dto) {
      State entity = mapper.toEntity(dto);
       entity = service.update(entity);
       return ResponseEntity.ok(mapper.toDto(entity));
    }

    @Override
    public ResponseEntity<Page<StateDTO>> read(
            @RequestBody StateDTO dto,
            @RequestParam("page") Integer page,
            @RequestParam("size") Integer size) {
        Pageable pageable = PageRequest.of(page,size);
        State entity = mapper.toEntity(dto);
        Page<StateDTO> pages = service.read(entity, pageable).map(mapper::toDto);
        return ResponseEntity.ok(pages);
    }

    @Override
    public ResponseEntity<StateDTO> readOne(@PathVariable("id") Integer primaryKey) {
         State entity = service.readOne(primaryKey);
         return ResponseEntity.ok(mapper.toDto(entity));
    }

    @Override
    public void delete(Integer primaryKey) {
        service.delete(primaryKey);
    }
}