package com.practice.todolist.controller;

import com.practice.todolist.model.Step;
import com.practice.todolist.controller.dto.StepDTO;
import com.practice.todolist.service.StepService;
import com.practice.todolist.service.mapper.StepMapper;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:26
*/
@RestController
@RequestMapping("/step-dto/")
public class StepControllerDTO implements CrudController<StepDTO,Integer>{

    @Autowired
    private StepService service;

    private StepMapper mapper;

    @Override
    public ResponseEntity<StepDTO> create(@RequestBody StepDTO dto) {
       Step entity = mapper.toEntity(dto);
       entity = service.create(entity);
       return ResponseEntity.ok(mapper.toDto(entity));
    }

    @Override
    public ResponseEntity<StepDTO> update(@RequestBody StepDTO dto) {
      Step entity = mapper.toEntity(dto);
       entity = service.update(entity);
       return ResponseEntity.ok(mapper.toDto(entity));
    }

    @Override
    public ResponseEntity<Page<StepDTO>> read(
            @RequestBody StepDTO dto,
            @RequestParam("page") Integer page,
            @RequestParam("size") Integer size) {
        Pageable pageable = PageRequest.of(page,size);
        Step entity = mapper.toEntity(dto);
        Page<StepDTO> pages = service.read(entity, pageable).map(mapper::toDto);
        return ResponseEntity.ok(pages);
    }

    @Override
    public ResponseEntity<StepDTO> readOne(@PathVariable("id") Integer primaryKey) {
         Step entity = service.readOne(primaryKey);
         return ResponseEntity.ok(mapper.toDto(entity));
    }

    @Override
    public void delete(Integer primaryKey) {
        service.delete(primaryKey);
    }
}