package com.practice.todolist.controller;

import com.practice.todolist.model.Step;
import com.practice.todolist.service.StepService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:26
*/
@RestController
@RequestMapping("/step/")
public class StepController implements CrudController<Step,Integer>{

    @Autowired
    private StepService service;

    @Override
    public ResponseEntity<Step> create(@RequestBody Step entity) {
        return ResponseEntity.ok(service.create(entity));
    }

    @Override
    public ResponseEntity<Step> update(@RequestBody Step entity) {
        return ResponseEntity.ok(service.update(entity));
    }

    @Override
    public ResponseEntity<Page<Step>> read(
            @RequestBody Step entity,
            @RequestParam("page") Integer page,
            @RequestParam("size") Integer size) {
        Pageable pageable = PageRequest.of(page,size);
        return ResponseEntity.ok(service.read(entity,pageable));
    }

    @Override
    @GetMapping("readOne/{id}")
    public ResponseEntity<Step> readOne(@PathVariable("id") Integer primaryKey) {
        return ResponseEntity.ok(service.readOne(primaryKey));
    }

    @Override
    public void delete(Integer primaryKey) {
        service.delete(primaryKey);
    }
}