package com.practice.todolist.controller;

import com.practice.todolist.model.Task;
import com.practice.todolist.controller.dto.TaskDTO;
import com.practice.todolist.service.TaskService;
import com.practice.todolist.service.mapper.TaskMapper;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:26
*/
@RestController
@RequestMapping("/task-dto/")
public class TaskControllerDTO implements CrudController<TaskDTO,Integer>{

    @Autowired
    private TaskService service;

    private TaskMapper mapper;

    @Override
    public ResponseEntity<TaskDTO> create(@RequestBody TaskDTO dto) {
       Task entity = mapper.toEntity(dto);
       entity = service.create(entity);
       return ResponseEntity.ok(mapper.toDto(entity));
    }

    @Override
    public ResponseEntity<TaskDTO> update(@RequestBody TaskDTO dto) {
      Task entity = mapper.toEntity(dto);
       entity = service.update(entity);
       return ResponseEntity.ok(mapper.toDto(entity));
    }

    @Override
    public ResponseEntity<Page<TaskDTO>> read(
            @RequestBody TaskDTO dto,
            @RequestParam("page") Integer page,
            @RequestParam("size") Integer size) {
        Pageable pageable = PageRequest.of(page,size);
        Task entity = mapper.toEntity(dto);
        Page<TaskDTO> pages = service.read(entity, pageable).map(mapper::toDto);
        return ResponseEntity.ok(pages);
    }

    @Override
    public ResponseEntity<TaskDTO> readOne(@PathVariable("id") Integer primaryKey) {
         Task entity = service.readOne(primaryKey);
         return ResponseEntity.ok(mapper.toDto(entity));
    }

    @Override
    public void delete(Integer primaryKey) {
        service.delete(primaryKey);
    }
}