package com.practice.todolist.controller.dto;

import lombok.Data;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:26
*/
@Data
public class TaskDTO {

    private long serialVersionUID;
    private int id;
    private java.lang.String description;
    private java.lang.String name;
    private int orderInSteplist;
    private com.practice.todolist.model.State stateBean;
    private com.practice.todolist.model.Step step;

}
