package com.practice.todolist.service.impl;

import com.practice.todolist.model.Listed;
import com.practice.todolist.repository.ListedRepository;
import com.practice.todolist.service.ListedService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:26
*/
@Service
public class ListedServiceBean implements ListedService {

    @Autowired
    private ListedRepository repository;

    @Override
    public Listed create(Listed entity) {
        return repository.save(entity);
    }

    @Override
    public Listed update(Listed entity) {
        return repository.save(entity);
    }

    @Override
    public Page<Listed> read(Listed entity, Pageable pageable) {
        Example<Listed> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public Listed readOne(Integer primaryKey) {
        return repository.getById(primaryKey);
    }

    @Override
    public void delete(Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}