package com.practice.todolist.service.impl;

import com.practice.todolist.model.State;
import com.practice.todolist.repository.StateRepository;
import com.practice.todolist.service.StateService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:26
*/
@Service
public class StateServiceBean implements StateService {

    @Autowired
    private StateRepository repository;

    @Override
    public State create(State entity) {
        return repository.save(entity);
    }

    @Override
    public State update(State entity) {
        return repository.save(entity);
    }

    @Override
    public Page<State> read(State entity, Pageable pageable) {
        Example<State> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public State readOne(Integer primaryKey) {
        return repository.getById(primaryKey);
    }

    @Override
    public void delete(Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}