package com.practice.todolist.service.impl;

import com.practice.todolist.model.Step;
import com.practice.todolist.repository.StepRepository;
import com.practice.todolist.service.StepService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:26
*/
@Service
public class StepServiceBean implements StepService {

    @Autowired
    private StepRepository repository;

    @Override
    public Step create(Step entity) {
        return repository.save(entity);
    }

    @Override
    public Step update(Step entity) {
        return repository.save(entity);
    }

    @Override
    public Page<Step> read(Step entity, Pageable pageable) {
        Example<Step> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public Step readOne(Integer primaryKey) {
        return repository.getById(primaryKey);
    }

    @Override
    public void delete(Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}