package com.practice.todolist.service.impl;

import com.practice.todolist.model.Task;
import com.practice.todolist.repository.TaskRepository;
import com.practice.todolist.service.TaskService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:25
*/
@Service
public class TaskServiceBean implements TaskService {

    @Autowired
    private TaskRepository repository;

    @Override
    public Task create(Task entity) {
        return repository.save(entity);
    }

    @Override
    public Task update(Task entity) {
        return repository.save(entity);
    }

    @Override
    public Page<Task> read(Task entity, Pageable pageable) {
        Example<Task> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public Task readOne(Integer primaryKey) {
        return repository.getById(primaryKey);
    }

    @Override
    public void delete(Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}