package com.practice.todolist.service;

import com.practice.todolist.model.Listed;

/**
* Generated by Springboot-3layer-Generator at 28.05.2021, 19:11:26
*/
public interface ListedService extends CrudService<Listed,Integer> {

}